entryPoints:
  web:
    # Listen on port 8081 for incoming requests
    address: :8888
  traefik:
    address: :9000
providers:
  # Enable the file provider to define routers / middlewares / services in file
  file:
    directory: /etc/traefik-config

log:
  level: DEBUG

experimental:
  localPlugins:
    dragonfly2imgproxy:
      moduleName: github.com/scrazy77/dragonfly2imgproxy
